import argparse

def option():
    parser = argparse.ArgumentParser(description='Reconstruct some image from a trained model.')
    parser.add_argument('--model', default='ResNet152', type=str)
    parser.add_argument('--pruning_rate', default=0.0, type=float)
    parser.add_argument('--gpu', default=0, type=int)
    parser.add_argument('--target_id', default=1000, type=int)
    parser.add_argument('--maxiter', default=24000, type=int)
    parser.add_argument('--restarts', default=1, type=int)
    parser.add_argument('--tv', default=0.1, type=float)
    parser.add_argument('--lr', default=0.1, type=float)
    parser.add_argument('--num_images', default=1, type=int)
    parser.add_argument('--data_path', default='data/',type=str)
    parser.add_argument('--exper_num', default='1', type=int)
    parser.add_argument('--epochs', default=120, type=int)
    parser.add_argument('--deterministic', action='store_true')
    parser.add_argument('--dataset', default='CIFAR10', type=str)
    parser.add_argument('--trained_model', action='store_true')
    parser.add_argument('--label_flip', action='store_true')
    parser.add_argument('--accumulation', default=0, type=int)
    parser.add_argument('--dtype', default='float', type=str)
    parser.add_argument('--optim', default='ours', type=str)
    parser.add_argument('--signed', action='store_false')
    parser.add_argument('--boxed', action='store_false')
    parser.add_argument('--cost_fn', default='sim', type=str)
    parser.add_argument('--optimizer', default='adam', type=str)
    parser.add_argument('--dryrun', action='store_true')
    parser.add_argument('--expnum', default=1, type=int)
    parser.add_argument('--save_image', action='store_true')
    return parser